# Site settings
title: Networkable Solutions
email: info@networkable.org
description: An open-source solution for your school's network.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.networkable.org" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
